### ISSUE TITLE
Optional Step 5 in Readme

### ISSUE THREAD

**Issue by DarthSidious666** [sepluginloader/SpaceEngineersLauncher#10]
Optional Step 5 isn't needed, you can instead use the Steam Launch properties and do this instead:

`D:\Steam\steamapps\common\SpaceEngineers\Bin64\SpaceEngineersLauncher.exe %command%`

which is the same as the Linux tip and works 100% whilst keeping the playtime incrementing properly.

**Comment by austinvaness** [comment]
I will remove the step since there are so many different ways to launch it. Does it really not count the playtime even though it says I am playing Space Engineers?

**Comment by DarthSidious666** [comment]
Yeah, usually if you add programs from outside Steam it doesn't count the playtime.
Of course I could be wrong with the way this hooks into Space Engineers.

I usually use this method for also bypassing useless clutter launchers and it works really well.

**Comment by austinvaness** [comment]
When the launcher starts, it creates a file called steam_appid.txt that tells steam it's Space Engineers. No matter how you start the launcher it should just work and track your playtime correctly. That's why steam shows you as being in SE when the launcher was used

**Comment by austinvaness** [comment]
Your right, the overlay appears to stop working if using the launch as external game method. However, I will not be adding a additional step to the instructions either way because it is much easier for the average person to just launch via shortcut. The overlay works fine when I launch it directly.
