### ISSUE TITLE
does not detect already running steam

### ISSUE THREAD

**Issue by Gusko-SVK** [sepluginloader/SpaceEngineersLauncher#14]
Greetings and thanks for your effort.
Sadly, the launcher doesn't work for me in ver 1.0.5.0.
I have the steam running, launcher is in Bin64.
Starting the launcher, I get the admin prompt for steam (I run steam as admin), but when I approve, there is a message that "Steam must be running before you can start Space Engineers."
Game used to run with plugin loader until recent versions, is running fine without plugin loader or launcher.
I'm using Win.7 SP1 (may/may not be related).
Any ideas?

Best regards,
G.

**Comment by austinvaness** [comment]
So steam is already running, and you start the launcher. Then when the launcher is starting you get an admin prompt for steam?

**Comment by Gusko-SVK** [comment]
Correct. And as soon as I approve of the steam being launched again (which does nothing), the launcher displays the message about steam not running.
+ info  has .NET Framework 4.8

**Comment by austinvaness** [comment]
Does it work correctly if you don't run steam as admin?

**Comment by Gusko-SVK** [comment]
Working.
Didn't ask for re-launch steam, updated the plugin loader, SE running.
It was the admin mode on steam.

Thanks for the tip and great work on the loader.

Best regards,
G.

**Comment by Gusko-SVK** [comment]
Thx for the tip, but I plan to postpone for as long as possible, due to other circumstances.
As for the steam compatibility, once it stops working I'll just give it the "imperative phallic gesture" and move on with life.

I will be watching for further versions of the launcher, since I need to run steam as an admin for other apps.
Thanks again.
o/

**Comment by austinvaness** [comment]
I wont be able to fix this because this is a steam issue. If you get that message, its because the steam API isn't detecting steam properly and the launcher is unable to hook into steam within 30 seconds of starting.
