### ISSUE TITLE
Launcher throws error on start and ignore leads to plugins not working.

### ISSUE THREAD

**Issue by me777** [sepluginloader/SpaceEngineersLauncher#18]
https://me777.de/SpaceEngineersLauncher.jpg

Thank you a lot.

**Comment by DirtyDerv** [comment]
yeah im getting the same

**Comment by soulscythe** [comment]
Seeing the same issue here.

**Comment by Doomgull** [comment]
Keen updated SE, will have to wait for the fix for that

**Comment by austinvaness** [comment]
Fixed in loader v1.11.5
