### ISSUE TITLE
Feature Request: Print error if in the wrong folder

### ISSUE THREAD

**Issue by kaedys** [sepluginloader/SpaceEngineersLauncher#19]
So, I was apparently a bit sleepy when reading the instructions, and dropped the EXE in the base folder of Space Engineers, rather than the Bin64 subdir.  Running the launcher from there appeared to do absolutely nothing, with no prompt for a log file and no displayed error (and obviously no game being run).  Displaying an error to double-check which directory the launcher EXE was in would have saved me a good 10 minutes of troubleshooting.

I'd also like to request that the suggestion from #10, for inserting the launcher as a Launch Option for SE in Steam, be added to the Readme, as it notable allows SE to be started, via the launcher, using Steam's normal "Play" button and/or the Steam tray right-click menu, rather than only via a shortcut to the launcher EXE.  It was rather fortuitous that I stumbled across that while trying to debug (and incidentally, trying to _add_ that to my Steam clued me in that I had the launcher in the wrong dir, as Steam started hollering that the game EXE didn't exist, because of course, it was in another directory >.<)

**Comment by austinvaness** [comment]
Fixed in v1.0.6
