### ISSUE TITLE
Windows AutoHDR doesn't seem to work

### ISSUE THREAD

**Issue by GeneralMine** [sepluginloader/SpaceEngineersLauncher#21]
Starting Space Engineers the regular way in steam windows 11 automatically turns on auto hdr for SE.
When starting it with the SpaceEngineersLauncher auto hdr doesn't seem to be applied to SE.

Can someone replicate and verify this? I might be wrong on this..

**Comment by austinvaness** [comment]
I don't have an HDR display, but from some quick research it looks like Microsoft is only allowing that to be used on specific programs. Have you tried adding the launcher as a game in steam, or using `"PathToLauncherHere" %command%` in the steam launch options for Space Engineers?

**Comment by GeneralMine** [comment]
Yeah I just added the line to the launch commands.
Its still not working. 

I also tested adding the SElauncher to the xbox game bar, but autohdr is still not detecting the game anymore. Is the launcher launching the original exe after configurating?

**Comment by austinvaness** [comment]
The original exe isn't started by the launcher in the traditional sense, instead the launcher will directly run the code for starting the game using keen's code from original exe.

**Comment by austinvaness** [comment]
I am almost positive that this will never work unless a plugin is introduced into the plugin list that gives the game native HDR support.
