### ISSUE TITLE
Plugin launcher isn't launching the game (version 1.0.5)

### ISSUE THREAD

**Issue by FestiveGears** [sepluginloader/SpaceEngineersLauncher#22]
I have followed AliceDoesThings' tutorial video and everything should be set up the way its supposed to be but for some reason whenever I try to launch the game nothing happens, I've tried setting it so that steam will launch the launcher when pressing "play" and it acts like its starting then proceeds to show "play" again rather than "stop" and nothing ever shows up. I'm very confused why it doesn't work. I've done everything the written instructions has said and the video has said too.

Any help would be greatly appreciated!

**Comment by FestiveGears** [comment]
When I try running as administrator it just says "Error: Space Engineers is already running!" but I've confirmed it is not through task manager. Just thought I should add this

**Comment by FestiveGears** [comment]
I've restarted steam and it still has the same error message

**Comment by austinvaness** [comment]
So the file is in the Bin64 folder next to SpaceEngineers.exe, and the launcher is unblocked in file properties?

**Comment by FestiveGears** [comment]
correct

**Comment by austinvaness** [comment]
Do you have an antivirus? Did you try restarting the PC? What windows version?

**Comment by FestiveGears** [comment]
yes, I'll try now and windows 11

**Comment by FestiveGears** [comment]
if you meant update version then 22H2

**Comment by FestiveGears** [comment]
ok so after a restart it started working. I don't know why I didn't think to try it earlier. Thank you, I'm going to close this thread now

**Comment by austinvaness** [comment]
Let me know if it happens again. I'm not sure how it got stuck like that in the first place
