### ISSUE TITLE
Program fails to launch

### ISSUE THREAD

**Issue by Brycey92** [sepluginloader/SpaceEngineersLauncher#24]
When I open the launcher exe from either Steam or directly from Windows Explorer, the cursor just spins for a second, and nothing happens.

**Comment by austinvaness** [comment]
Did you put it in the bin64 folder? SpaceEngineers.Exe and the other dll files should be in the same folder.

**Comment by Brycey92** [comment]
Ohhh, I expected it to work more like a modloader that searches for the game files! I somehow also completely missed the readme. 😅 Might be nice to pop up a dialog saying that it needs to be next to SpaceEngineers.exe, but it's by no means a requirement.

Just confirmed this launches properly when one reads and follows instructions 😂👍
