### ISSUE TITLE
Can't find SpaceEngineers.exe

### ISSUE THREAD

**Issue by erikpopp** [sepluginloader/SpaceEngineersLauncher#25]
When I open the space engineers launcher, this is the error that I get. Could you make SpaceEngineersLauncher check the place(s) where SpaceEngineers.exe is normally located instead of relying only on it being in the same folder?
![Error Message - Can't Find SpaceEngineers](https://github.com/sepluginloader/SpaceEngineersLauncher/assets/13426770/5d03c88e-b92f-48f2-b5e1-faec7eae9689)

**Comment by austinvaness** [comment]
This is a very old issue but I will post this in case anyone else finds it.

This error only appears if you put the SpaceEngineersLauncher.exe in the wrong place. It has to be in the same folder as the SpaceEngineers.exe file (which is the game's Bin64 folder).
