### ISSUE TITLE
Plugins Menu Causes Immediate CTD

### ISSUE THREAD

**Issue by GwalchgwynGemau** [sepluginloader/SpaceEngineersLauncher#33]
It seems that the game crashes the moment that I click on the Plugin menu item: I have no plugins installed, but the latest version I've tried is 1.0.6 - is there a newer version, am I doing something wrong, or is this just dead now?

**Comment by austinvaness** [comment]
This project hasn't been updated because it is just the launcher. This is the main project: https://github.com/sepluginloader/PluginLoader

Are you running Windows? Latest game version? After replicating the issue please upload your latest game .log file from %appdata%/SpaceEngineers

**Comment by GwalchgwynGemau** [comment]
My apologies for the confusion.

I was about to provide more detail (including steps that I have taken), but upon testing this morning, it's all working as expected!

To clarify, I'm on Windows 10, latest version of SE, launcher 1.0.6, and the plugin loader version is 1.12.5. Nothing has changed since the last failure, but it is all good now. I hate to have wasted anyone's time.

I think I'll run image and SFC checks on my machine, just in case.

Nothing to see here.... -_-
