### ISSUE TITLE
Doesn't launch Steam anymore (minor)

### ISSUE THREAD

**Issue by dionysius** [sepluginloader/SpaceEngineersLauncher#38]
It used to and still says in the launcher it tries to open steam, but nothing happens. Also no error shown, it just doesn't launch Steam and the launcher window just goes away after a bit. No deal breaker, I just open Steam myself beforehand. After opening Steam everything works fine.

**Comment by austinvaness** [comment]
What happens if you press Win+R to open the run box and enter `steam://`?

**Comment by dionysius** [comment]
Well today it launched Steam. Couldn't test your question.
