### ISSUE TITLE
No "SpaceEngineersLauncher.exe" file..?

### ISSUE THREAD

**Issue by NickyLunaLove** [sepluginloader/SpaceEngineersLauncher#4]
Uhhhhh...yeah, there is no file of that name in the zip...actually there is no exe file what so ever. I tried to put the path into the advanced launch options on steam, as formatted in the instructions (with my specific path of course), and it just says "no .exe found"...help?

**Comment by mrfosse** [comment]
I had the same issue, the 1.202 version is for a future update of SE i think. I got it working using the instructions for the 1.201 version linked here:

https://github.com/sepluginloader/PluginLoader

**Comment by viktor-ferenczi** [comment]
Yes, the issue here is that putting any instructions online which is applicable to a future game version is just confusing for regular players. I guess most players are not aware of the game's version number, which is normal. We cannot expect them to do so.

**Comment by NickyLunaLove** [comment]
Thanks, guys :)
