### ISSUE TITLE
Where's the Launcher exe?

### ISSUE THREAD

**Issue by SnowmanDK** [sepluginloader/SpaceEngineersLauncher#5]
The instructions in the readme refers to https://github.com/sepluginloader/SpaceEngineersLauncher/releases/latest where I should be able to download the latest Launcher exe, but there are only 2 source code packages.

**Comment by viktor-ferenczi** [comment]
The ZIP file will be there once the upcoming major game update (1.202) is released.

The current game version (1.201.014) is still using the DLL version of Plugin Loader.

Sorry for the confusion.

**Comment by Bejasc** [comment]
Does this mean it's not possible to use plugin loader at all, until the version has released?

Joining any DS with the dll / launch options method causes a CTD

**Comment by viktor-ferenczi** [comment]
Please post your game and loader logs here or on the [Plugin Loader Discord](https://discord.gg/6ETGRU3CzR) into a new ticket on the `#support` channel. Please also see the `#troubleshooting` Discord channel for the most common issues.

Latest `SpaceEngineers_*.log` file by date from the `%AppData%\SpaceEngineers` directory.

Loader log should be in `C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64\Plugins`, unless you moved the game files to somewhere else.

**Comment by viktor-ferenczi** [comment]
Please join the [Plugin Loader Discord](https://discord.gg/6ETGRU3CzR) and post your problem and SE log file under the `#support` channel. We will try to help.
