### ISSUE TITLE
Where is the list of enabled plugins on disk?

### ISSUE THREAD

**Issue by soulscythe** [sepluginloader/SpaceEngineersLauncher#6]
One (or maybe more) of the plugins I choose to use seems incompatible with the latest update, and the game crashes at startup when using the plugin launcher. Since I can't launch with the launcher, I can't access the in-game plugin list to disable any potential troublemakers. Please advise what file I should edit to modify this outside the game.

**Comment by soulscythe** [comment]
For further info, I tried removing entries from "Bin64\Plugins\config.xml", but the file was restored when next running the plugin launcher, so it obviously has the data stored elsewhere

**Comment by austinvaness** [comment]
Do you have a game log? There are multiple stages of startup now. The first time you see the Plugin Loader splash screen its the launcher stage and its not really supposed to be doing anything except keep Plugin Loader up to date. The second time you see the loader splash screen is when all the plugins start being loaded. Also, deleting config.xml is how you would disable all plugins so it must be some other issue.

**Comment by soulscythe** [comment]
Sure, here's the most recent log. This doesn't happen when launching normally (without the launcher), and it didn't happen on the first launch with the launcher either. I decided to try out some other plugins I hadn't used before, and then on the restart just then, it crashed, and has done since. 

Also, for the record, every time it crashes like this, I need to verify file integrity in steam and re-download 2 files, totalling 24gb-ish, otherwise I can't launch the game in any state, launcher or not. 

[SpaceEngineers_20230413_221354739.log](https://github.com/sepluginloader/SpaceEngineersLauncher/files/11228614/SpaceEngineers_20230413_221354739.log)

**Comment by soulscythe** [comment]
Ok, fully deleting the Bin64\Plugins folder, along with the plugin loader .dll, then letting the launcher redownload everything seems to have allowed me to launch (using launcher) without a crash. However, enabling some of the plugins resulted in the same thing again - a crash that forces me to verify the game files and redownload all the plugins. 

After trying again, it seems to reliably to be this `VRageRender.MyRenderException: Failed to compile Lighting/LightSpot.hlsl` in the logs whenever it crashes, but I'm not certain why this exception is happening. I will continue and see which plugins I can actually use without errors popping up, however every time it crashes the whole file verification and redownloading takes 40-50 minutes.

**Comment by austinvaness** [comment]
It sounds like its being caused by a certain plugin so let me know if you find out which one

**Comment by austinvaness** [comment]
This issue may have been caused by Reflective Water by Jakaria. I just removed it since he said it is not needed anymore.

**Comment by soulscythe** [comment]
Hi, yes sorry I hadn't played in a bit as I had been busy. Anyway yes I had suspected that plugin in particular myself, given it was rendering related and I hadn't used it before. I haven't had issues since anyway, and I disabled that plugin among a few others. 

We'll assume that was the issue and leave it at that. Thank you for your time.
