### ISSUE TITLE
Skipintro

### ISSUE THREAD

**Issue by dtmaster79** [sepluginloader/SpaceEngineersLauncher#7]
Are there start options like -skipintro? It's annoying that I have the intro again. And I don't want to add it as a non-steam game to steam. Can you please install this?

**Comment by viktor-ferenczi** [comment]
You can pass the `-skipintro` parameter to the launcher. Have you tried that? Does it work?

In addition to the above parameter you can do more to make SE faster to start and stop:
- Rename the `C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Content\Videos` folder (your installation may be at a different place) and create an empty `Videos` folder instead
- Install these plugins:
  * Instant Exit
  * No News Plugin
  * In Game Exit

**Comment by austinvaness** [comment]
If you don't want to mess around with launch options I recommend the "Remove Intro Video" plugin

**Comment by viktor-ferenczi** [comment]
Added to the list above. We may want to copy the above info to some Troubleshooting doc/site.
