### ISSUE TITLE
how do i get it to work 

### ISSUE THREAD

**Issue by Deadmen6661** [sepluginloader/SpaceEngineersLauncher#8]
ive tried to get it to work all the ways github and google say nothing works

**Comment by viktor-ferenczi** [comment]
Could you please give me a bit more information? What is the exact problem? We cannot help you if you don't give us any details...

You're more than welcome to join the [Plugin Loader Discord](https://discord.gg/6ETGRU3CzR) and create a ticket on the `#support` channel.
