### ISSUE TITLE
Video Adapter not picking up correct one 

### ISSUE THREAD

**Issue by JacoVanEck** [sepluginloader/SpaceEngineersLauncher#9]
I did all the steps as requested to make it work . 
It is launching the game but then I get an error "We have detected a better graphics card " 
If I go to the adapter settings on the no plugin game there is 3 in the list 
![3 option](https://user-images.githubusercontent.com/28974820/232465873-2e8ede45-8ddf-48ba-ab4e-f00648de93d1.jpg)
With the first one being the selected true one . 
When i launch the game via the launcher of the plugin one i only see 2 there and thus when i play the game as is its lagging 
![2 option ](https://user-images.githubusercontent.com/28974820/232465849-1881f2dd-f9e9-4035-9ed6-6a52e7d4f53a.jpg)

I am unsure if this is something you can fix but worth a try to reach out if u have advice.

**Comment by austinvaness** [comment]
I'm still not sure why this happens. I will work on getting a cpu with integrated graphics to test this. 

Is there a GPU setting in the Nvidia control panel to set SpaceEngineersLauncher.exe to use the dedicated GPU?

**Comment by JacoVanEck** [comment]
I had a quick look and cant find anything yet 
I will re look later if I do see something

**Comment by viktor-ferenczi** [comment]
**geForce Experience** is recognizing SE as a game:
![image](https://user-images.githubusercontent.com/1848514/232534648-5430f712-5626-40b5-8a48-1d6a6c07c071.png)

There is some "Optimize" and "Launch" there. In it Settings there is a checkbox:
![image](https://user-images.githubusercontent.com/1848514/232534881-8b6ccb7d-60ce-4569-b386-0c5cb6064e50.png)

Maybe this is screwing with the game'd display options.

Just an idea...

**Comment by JacoVanEck** [comment]
I cant add a new game on the GeForce side . 
the Space engineer game works 100% just not the plugin side of things

**Comment by austinvaness** [comment]
Does the latest version of the launcher (1.0.2) change anything at all?

**Comment by JacoVanEck** [comment]
No it does not i downloaded the new one yesterday

**Comment by austinvaness** [comment]
The one I posted a few hours ago??

**Comment by JacoVanEck** [comment]
o no i did not realize there a new new one like that , sorry i will get that and try that

**Comment by JacoVanEck** [comment]
Still the same 
![image](https://user-images.githubusercontent.com/28974820/232871903-998ed9f0-f237-4f48-a225-1a7b22c6adf0.png)

**Comment by austinvaness** [comment]
Check the default gpu in windows settings. Try following these instructions for a desktop app but for your GTX 1660: https://www.amd.com/en/support/kb/faq/gpu-110

**Comment by JacoVanEck** [comment]
i will try that and let you know thanx

**Comment by JacoVanEck** [comment]
That looks like it might have done it !!! 
I loaded the game after adding it as a game in widows and telling it its high performance .
THANK YOU SO MUCH
